const authTypes = {
  TOKEN_PENDING: 'TOKEN_PENDING',
  TOKEN_ERROR: 'TOKEN_ERROR',
  TOKEN_SUCCESS: 'TOKEN_SUCCESS',
  GET_TOKEN: 'GET_TOKEN',
  SIGNUP_PENDING: 'SIGNUP_PENDING',
  SIGNUP_ERROR: 'SIGNUP_ERROR',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP: 'SIGNUP',
}

export default authTypes
