const authTypes = {
  TOKEN_PENDING: 'TOKEN_PENDING',
  TOKEN_ERROR: 'TOKEN_ERROR',
  TOKEN_SUCCESS: 'TOKEN_SUCCESS',
  GET_TOKEN: 'GET_TOKEN',
  SIGNUP_PENDING: 'SIGNUP_PENDING',
  SIGNUP_ERROR: 'SIGNUP_ERROR',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP: 'SIGNUP',
  SIGNIN_PENDING: 'SIGNIN_PENDING',
  SIGNIN_ERROR: 'SIGNIN_ERROR',
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN: 'SIGNIN',
  GET_PROFILE: 'GET_PROFILE',
  PROFILE_SUCCESS: 'PROFILE_SUCCESS'
}

export default authTypes
