const charactersTypes = {
  CHARACTERS_PENDING: 'CHARACTERS_PENDING',
  CHARACTERS_ERROR: 'CHARACTERS_ERROR',
  CHARACTERS_SUCCESS: 'CHARACTERS_SUCCESS',
  GET_CHARACTERS: 'GET_CHARACTERS',
  GET_FAVORITES: 'GET_FAVORITES',
  GET_CHARACTER: 'GET_CHARACTER',
  CHARACTER_ERROR: 'CHARACTER_ERROR',
  CHARACTER_SUCCESS: 'CHARACTER_SUCCESS',
}

export default charactersTypes
