const charactersTypes = {
  CHARACTERS_PENDING: 'CHARACTERS_PENDING',
  CHARACTERS_ERROR: 'CHARACTERS_ERROR',
  CHARACTERS_SUCCESS: 'CHARACTERS_SUCCESS',
  GET_CHARACTERS: 'GET_CHARACTERS',
  GET_FAVORITES: 'GET_FAVORITES'
}

export default charactersTypes
